version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms-app2
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_ACCESS_TOKEN_SECRET: ${JWT_ACCESS_TOKEN_SECRET}
      JWT_REFRESH_TOKEN_SECRET: ${JWT_REFRESH_TOKEN_SECRET}

  db:
    image: postgres:15-alpine
    container_name: lms-db2
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: lms-redis
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
