version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile      # <-- your build settings
    container_name: lms-app        # <-- now at the same level as `build:`
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    env_file:
      - .env  
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}

  db:
    image: postgres:15-alpine
    container_name: lms-db        # <-- also at this level
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: lms-redis
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
