version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms-app
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    container_name: lms-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: lms-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
  