name: "Server deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DB_HOST }}
          username: ${{ secrets.DB_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "🚀 Loyihani tayyorlash boshlanmoqda..."

            cd /home/ubuntu/

            if [ ! -d "start-up" ]; then
              echo "📥 Git repozitoriyasini klonlash..."
              git clone https://github.com/aziz-davronov107/start-up.git
            fi

            echo "🔄 Repozitoriyani yangilash..."
            cd start-up
            git pull origin main


            echo "🧹 Docker konteynerlar va volume tozalanmoqda..."
            docker compose down -v

            echo "🏗️ Docker image'lar --no-cache bilan qayta build qilinmoqda..."
            docker compose build --no-cache

            echo "🔥 Docker konteynerlar ishga tushirilmoqda..."
            docker compose up -d

            echo "📜 Loglar: "
            echo "✅ Deploy muvaffaqiyatli yakunlandi!"
